policy:
  # Bug Report - Platform labels from OS dropdown
  - template: [ '01-bug-report.yml' ]
    section:
      - id: [ 'operating_system' ]
        block-list: [ ]
        label:
          - name: 'macos'
            keys: [ 'macOS (Intel or Apple Silicon)' ]
          - name: 'windows'
            keys: [ 'Windows (x86_64 or ARM64)' ]
          - name: 'linux'
            keys: [ 'Linux (x86_64 or ARM64)' ]

  # Performance Issue - Platform labels from OS dropdown
  - template: [ '03-performance-issue.yml' ]
    section:
      - id: [ 'operating_system' ]
        block-list: [ ]
        label:
          - name: 'macos'
            keys: [ 'macOS (Intel or Apple Silicon)' ]
          - name: 'windows'
            keys: [ 'Windows (x86_64 or ARM64)' ]
          - name: 'linux'
            keys: [ 'Linux (x86_64 or ARM64)' ]

  # Standards/CDISC Issue - Standard labels from dropdown
  - template: [ '05-standards-cdisc.yml' ]
    section:
      - id: [ 'standarddomain' ]
        block-list: [ 'Other' ]
        label:
          - name: 'SDTM'
            keys: [ 'SDTM (Study Data Tabulation Model)' ]
          - name: 'ADaM'
            keys: [ 'ADaM (Analysis Data Model)' ]
          - name: 'SEND'
            keys: [ 'SEND (Standard for Exchange of Nonclinical Data)' ]
          - name: 'CT'
            keys: [ 'Controlled Terminology' ]
          - name: 'Define-XML'
            keys: [ 'Define-XML' ]
          - name: 'Dataset-XML'
            keys: [ 'Dataset-XML Format' ]
          - name: 'XPT'
            keys: [ 'XPT Format (V5 or V8)' ]
