"""Constants and patterns for SDTM mapping inference.

This module contains the pattern dictionaries used for inferring SDTM variable
names from source column names.
"""

from __future__ import annotations

# Patterns for inferring SDTM variable names from source column names
# These patterns map normalized source column names to SDTM variables
SDTM_INFERENCE_PATTERNS: dict[str, dict[str, list[str]]] = {
    # Global patterns (apply to all domains)
    "_GLOBAL": {
        "USUBJID": [
            "SUBJECTID",
            "SUBJECTIDENTIFIER",
            "PATIENTID",
            "SUBJECT",
            "PATIENTIDENTIFIER",
        ],
        "SEX": ["SEX", "GENDER"],
        "AGE": ["AGE"],
        "AGEU": ["AGEU", "AGEUNIT", "AGEUNITS"],
        "RACE": ["RACE"],
        "ETHNIC": ["ETHNIC", "ETHNICITY"],
        "RFSTDTC": ["ICDAT", "INFORMEDCONSENTDATE", "RFSTDTC"],
        "BRTHDTC": ["BRTHDTC", "BIRTHDATE", "DOB"],
        "COUNTRY": ["COUNTRY", "COUNTRYCD"],
        "SITEID": ["SITEID", "SITECODE", "SITE"],
        "EPOCH": ["EPOCH", "VISITEPOCH"],
        "TAETORD": ["TAETORD", "ELEMENTORDER", "PLANNEDORDER"],
        "VISITNUM": ["VISITNUM", "VISITNUMBER"],
        "VISIT": ["VISIT", "VISITNAME", "EVENTNAME"],
        "VISITDY": ["VISITDY", "PLANNEDSTUDYDAYOFVISIT"],
        "SPDEVID": ["SPDEVID", "DEVICEID", "DEVICEIDENTIFIER"],
    },
    # Domain-specific patterns (--VARIABLE becomes DOMAIN + VARIABLE)
    "_DOMAIN_SUFFIXES": {
        "TERM": ["TERM", "REPORTEDTERM", "VERBATIM"],
        "DECOD": ["DECOD", "DECODE", "DICTIONARYTERM", "STANDARDTERM"],
        "CAT": ["CAT", "CATEGORY"],
        "SCAT": ["SCAT", "SUBCATEGORY"],
        "ORRES": ["ORRES", "RESULT", "ORIGINALRESULT", "VALUE"],
        "ORRESU": ["ORRESU", "UNIT", "UNITS", "ORIGINALUNIT"],
        "STRESC": ["STRESC", "STANDARDRESULT", "STANDARDIZEDRESULT"],
        "STRESN": ["STRESN", "NUMERICRESULT", "NUMERICVALUE"],
        "STRESU": ["STRESU", "STANDARDUNIT"],
        "SEQ": ["SEQ", "EVENTSEQ", "SEQUENCENUMBER", "EVENTSEQUENCENUMBER"],
        "GRPID": ["GRPID", "GROUPID", "GROUP"],
        "REFID": ["REFID", "REFERENCEID", "REFIDENTIFIER"],
        "SPID": ["SPID", "SPONSORID", "SPONSORIDENTIFIER"],
        "LNKID": ["LNKID", "LINKID", "LINKIDENTIFIER", "LINK"],
        "LNKGRP": ["LNKGRP", "LINKGROUP", "LINKGRP"],
        "STDTC": ["STDTC", "STDAT", "STARTDATE", "STARTDATETIME"],
        "ENDTC": ["ENDTC", "ENDAT", "ENDDATE", "ENDDATETIME"],
        "DTC": ["DTC", "DAT", "DATE", "DATETIME"],
        "RFTDTC": ["RFTDTC", "REFERENCEDTC", "REFERENCETIMEPOINT"],
        "DY": ["DY", "STUDYDAY"],
        "STDY": ["STDY", "STARTDY", "STUDYDAYSTART"],
        "ENDY": ["ENDY", "ENDDY", "STUDYDAYEND"],
        "DUR": ["DUR", "DURATION"],
        "ELTM": ["ELTM", "ELAPSEDTIME", "ELAPSED"],
        "TPT": ["TPT", "TIMEPOINT", "PLANNEDTIMEPOINT"],
        "TPTNUM": ["TPTNUM", "TIMEPOINTNUM", "TPTNUMBER"],
        "TPTREF": ["TPTREF", "TIMEPOINTREF", "REFERENCEPOINT"],
        "STRTPT": ["STRTPT", "STARTTPT", "STARTREFERENCE"],
        "STTPT": ["STTPT", "STARTTP", "STARTTIMEPOINT"],
        "ENRTPT": ["ENRTPT", "ENDRTPT", "ENDREFERENCEPOINT"],
        "ENTPT": ["ENTPT", "ENDTPT", "ENDTIMEPOINT"],
        "ENRF": ["ENRF", "ENDREF", "ENDREFERENCE"],
        "STRF": ["STRF", "STARTREF", "STARTREFERENCE"],
        "STAT": ["STAT", "STATUS", "COMPLETIONSTATUS"],
        "REASND": ["REASND", "REASONNOTDONE", "REASON"],
        "TEST": ["TEST", "TESTNAME"],
        "TESTCD": ["TESTCD", "TESTCODE"],
        "POS": ["POS", "POSITION"],
        "PERF": ["PERF", "PERFORMED"],
        "BODSYS": ["BODSYS", "BODYSYSTEM", "ORGANCLASS"],
        "LOC": ["LOC", "LOCATION", "SITE"],
        "LAT": ["LAT", "LATERALITY"],
        "DIR": ["DIR", "DIRECTION"],
        "METHOD": ["METHOD", "COLLECTIONMETHOD"],
        "SPEC": ["SPEC", "SPECIMEN", "SPECIMENTYPE"],
        "TRT": ["TRT", "TREATMENT", "MEDICATION", "DRUG"],
        "DOSE": ["DOSE", "DOSEAMOUNT"],
        "DOSU": ["DOSU", "DOSEUNIT", "DOSEUNITS"],
        "DOSFRM": ["DOSFRM", "DOSEFORM"],
        "DOSFRQ": ["DOSFRQ", "DOSINGFREQUENCY", "FREQUENCY"],
        "ROUTE": ["ROUTE", "ADMINISTRATIONROUTE"],
        "SER": ["SER", "SERIOUS", "SERIOUSEVENT"],
        "SEV": ["SEV", "SEVERITY", "INTENSITY"],
        "REL": ["REL", "RELATIONSHIP", "CAUSALITY"],
        "OUT": ["OUT", "OUTCOME"],
        "ACN": ["ACN", "ACTION", "ACTIONTAKEN"],
    },
}
