name: "\u2728 Feature Request"
description: "Propose a new feature or enhancement"
title: "[Feature]: "
labels: [ "enhancement", "needs triage" ]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: A clear description of the problem you're trying to solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area/Crate
      description: Which area of the application does this affect?
      options:
        - GUI / User Interface
        - XPT Export (V5/V8)
        - Dataset-XML Export
        - Define-XML Export
        - Data Validation
        - Column Mapping
        - CSV Import/Ingestion
        - CDISC Standards
        - Auto-Updates
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe any alternative solutions you've considered...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Screenshots, mockups, references, or examples...
    validations:
      required: false

  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have read and agree to the [Code of Conduct](https://github.com/rubentalstra/Trial-Submission-Studio/blob/main/CODE_OF_CONDUCT.md)
          required: true
