"""Constants and templates for SAS code generation.

This module contains SAS code templates and configuration constants.
"""

from __future__ import annotations

# SAS program template for SDTM domain transformation
SAS_PROGRAM_TEMPLATE = """/* Generated by CDISC Transpiler */
/* Domain: {{ domain.code }} */
/* Generated: {{ timestamp }} */

DATA {{ output_dataset }};
    SET {{ input_dataset }};
    length
    {%- for variable in domain.variables %}
        {{ variable.name }} ${{ variable.length }}
    {%- endfor %}
    ;

    /* Column mappings */
    {%- for assignment in assignments %}
    {{ assignment }}
    {%- endfor %}

    /* Defaulted required fields */
    {%- for default_line in default_assignments %}
    {{ default_line }}
    {%- endfor %}

    STUDYID = "{{ study_id }}";
    DOMAIN = "{{ domain.code }}";

    KEEP {{ keep_clause }};
RUN;
"""

# Default study ID when none is provided
DEFAULT_STUDY_ID = "STUDY"

# Default encoding for SAS files
SAS_FILE_ENCODING = "utf-8"
