//! Action components for the Mapping tab.
//!
//! Contains mapping actions and the not-collected inline edit form.

use iced::widget::{Space, button, column, row, text, text_input};
use iced::{Alignment, Border, Element, Length, Theme};
use iced_fonts::lucide;

use crate::component::display::{ActionButton, ActionButtonList};
use crate::message::domain_editor::MappingMessage;
use crate::message::{DomainEditorMessage, Message};
use crate::state::{NotCollectedEdit, SourceDomainState};
use crate::theme::{
    BORDER_RADIUS_SM, ClinicalColors, SPACING_MD, SPACING_SM, SPACING_XS, button_primary,
    button_secondary,
};

use tss_standards::CoreDesignation;
use tss_submit::VariableStatus;

// =============================================================================
// ACTIONS
// =============================================================================

pub(super) fn view_mapping_actions<'a>(
    source: &'a SourceDomainState,
    var: &'a tss_standards::SdtmVariable,
    status: VariableStatus,
) -> Element<'a, Message> {
    let var_name = var.name.clone();
    let mut actions = ActionButtonList::new().title("Actions");

    // Clear mapping (if mapped)
    if matches!(status, VariableStatus::Accepted) {
        actions = actions.button(ActionButton::secondary_themed(
            lucide::x().size(12),
            |theme: &Theme| theme.clinical().text_secondary,
            "Clear Mapping",
            Message::DomainEditor(DomainEditorMessage::Mapping(MappingMessage::ClearMapping(
                var_name.clone(),
            ))),
        ));
    }

    // Mark Not Collected (Expected variables that are not mapped)
    if var.core == Some(CoreDesignation::Expected)
        && !matches!(
            status,
            VariableStatus::Accepted | VariableStatus::NotCollected | VariableStatus::AutoGenerated
        )
    {
        actions = actions.button(ActionButton::secondary_themed(
            lucide::ban().size(12),
            |theme: &Theme| theme.clinical().text_secondary,
            "Mark Not Collected",
            Message::DomainEditor(DomainEditorMessage::Mapping(
                MappingMessage::MarkNotCollected {
                    variable: var_name.clone(),
                },
            )),
        ));
    }

    // Edit reason + Revert (if NotCollected)
    if matches!(status, VariableStatus::NotCollected) {
        let current_reason = source
            .mapping
            .not_collected_reason(&var.name)
            .unwrap_or("")
            .to_string();
        actions = actions.button(ActionButton::secondary_themed(
            lucide::pencil().size(12),
            |theme: &Theme| theme.clinical().text_secondary,
            "Edit Reason",
            Message::DomainEditor(DomainEditorMessage::Mapping(
                MappingMessage::EditNotCollectedReason {
                    variable: var_name.clone(),
                    current_reason,
                },
            )),
        ));
        actions = actions.button(ActionButton::secondary_themed(
            lucide::undo().size(12),
            |theme: &Theme| theme.clinical().text_secondary,
            "Revert to Mapping",
            Message::DomainEditor(DomainEditorMessage::Mapping(
                MappingMessage::ClearNotCollected(var_name.clone()),
            )),
        ));
    }

    // Mark Omit (Permissible variables)
    if (var.core.is_none() || var.core == Some(CoreDesignation::Permissible))
        && !matches!(
            status,
            VariableStatus::Accepted | VariableStatus::Omitted | VariableStatus::AutoGenerated
        )
    {
        actions = actions.button(ActionButton::secondary_themed(
            lucide::eye_off().size(12),
            |theme: &Theme| theme.clinical().text_secondary,
            "Omit from Output",
            Message::DomainEditor(DomainEditorMessage::Mapping(MappingMessage::MarkOmitted(
                var_name.clone(),
            ))),
        ));
    }

    // Clear Omit (if omitted)
    if matches!(status, VariableStatus::Omitted) {
        actions = actions.button(ActionButton::secondary_themed(
            lucide::eye().size(12),
            |theme: &Theme| theme.clinical().text_secondary,
            "Include in Output",
            Message::DomainEditor(DomainEditorMessage::Mapping(MappingMessage::ClearOmitted(
                var_name,
            ))),
        ));
    }

    actions.view_or_empty()
}

// =============================================================================
// NOT COLLECTED INLINE EDIT
// =============================================================================

pub(super) fn view_not_collected_inline_edit<'a>(
    var: &'a tss_standards::SdtmVariable,
    edit: &'a NotCollectedEdit,
) -> Element<'a, Message> {
    let var_name = var.name.clone();
    let reason = edit.reason.clone();
    let reason_for_save = reason.clone();

    let char_count = reason.len();
    let max_len = 200;
    let is_over = char_count > max_len;
    let is_empty = reason.trim().is_empty();
    let can_save = !is_empty && !is_over;

    let reason_input = text_input("Enter reason why data was not collected...", &reason)
        .on_input(|s| {
            Message::DomainEditor(DomainEditorMessage::Mapping(
                MappingMessage::NotCollectedReasonChanged(s),
            ))
        })
        .padding([10.0, 12.0])
        .size(14)
        .style(move |theme: &Theme, _| {
            let clinical = theme.clinical();
            let border_color = if is_over || is_empty {
                clinical.border_error
            } else {
                clinical.border_default
            };
            iced::widget::text_input::Style {
                background: clinical.background_elevated.into(),
                border: Border {
                    color: border_color,
                    width: 1.0,
                    radius: BORDER_RADIUS_SM.into(),
                },
                icon: clinical.text_muted,
                placeholder: clinical.text_disabled,
                value: theme.extended_palette().background.base.text,
                selection: theme.extended_palette().primary.base.color,
            }
        });

    let error_msg: Element<'a, Message> = if is_empty {
        text("Reason is required")
            .size(11)
            .style(|theme: &Theme| text::Style {
                color: Some(theme.extended_palette().danger.base.color),
            })
            .into()
    } else if is_over {
        text("Reason too long")
            .size(11)
            .style(|theme: &Theme| text::Style {
                color: Some(theme.extended_palette().danger.base.color),
            })
            .into()
    } else {
        Space::new().height(0.0).into()
    };

    let save_btn = button(
        row![
            lucide::check().size(12),
            Space::new().width(SPACING_XS),
            text("Save").size(13)
        ]
        .align_y(Alignment::Center),
    )
    .on_press_maybe(if can_save {
        Some(Message::DomainEditor(DomainEditorMessage::Mapping(
            MappingMessage::NotCollectedSave {
                variable: var_name,
                reason: reason_for_save,
            },
        )))
    } else {
        None
    })
    .padding([8.0, 16.0])
    .style(button_primary);

    let cancel_btn = button(text("Cancel").size(13))
        .on_press(Message::DomainEditor(DomainEditorMessage::Mapping(
            MappingMessage::NotCollectedCancel,
        )))
        .padding([8.0, 16.0])
        .style(button_secondary);

    column![
        text("Not Collected Reason")
            .size(14)
            .style(|theme: &Theme| text::Style {
                color: Some(theme.clinical().text_secondary)
            }),
        Space::new().height(SPACING_SM),
        row![
            text("Reason *")
                .size(12)
                .style(|theme: &Theme| text::Style {
                    color: Some(theme.clinical().text_muted)
                }),
            Space::new().width(Length::Fill),
            text(format!("{}/{}", char_count, max_len))
                .size(11)
                .style(move |theme: &Theme| text::Style {
                    color: Some(if is_over {
                        theme.extended_palette().danger.base.color
                    } else {
                        theme.clinical().text_disabled
                    })
                }),
        ],
        Space::new().height(4.0),
        reason_input,
        error_msg,
        Space::new().height(SPACING_MD),
        row![save_btn, Space::new().width(SPACING_SM), cancel_btn],
    ]
    .into()
}
