"""SAS code generation."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from jinja2 import Environment, StrictUndefined

from .mapping import MappingConfig
from .domains import SDTMDomain, get_domain
from .normalizers import render_assignment

_TEMPLATE = """/* Generated by CDISC Transpiler */
/* Domain: {{ domain.code }} */
/* Generated: {{ timestamp }} */

DATA {{ output_dataset }};
    SET {{ input_dataset }};
    length
    {%- for variable in domain.variables %}
        {{ variable.name }} ${{ variable.length }}
    {%- endfor %}
    ;

    /* Column mappings */
    {%- for assignment in assignments %}
    {{ assignment }}
    {%- endfor %}

    /* Defaulted required fields */
    {%- for default_line in default_assignments %}
    {{ default_line }}
    {%- endfor %}

    STUDYID = "{{ study_id }}";
    DOMAIN = "{{ domain.code }}";

    KEEP {{ keep_clause }};
RUN;
"""

_env = Environment(trim_blocks=True, lstrip_blocks=True, undefined=StrictUndefined)
_template = _env.from_string(_TEMPLATE)


def generate_sas_program(
    domain_code: str,
    config: MappingConfig,
    input_dataset: str,
    output_dataset: str,
) -> str:
    domain = get_domain(domain_code)
    assignments = [
        _assignment_for_mapping(mapping, domain) for mapping in config.mappings
    ]
    default_assignments = _default_missing(domain, config)
    keep_clause = " ".join(domain.variable_names())
    study_id = config.study_id or "STUDY"
    payload = _template.render(
        domain=domain,
        timestamp=datetime.now(UTC).isoformat(timespec="seconds"),
        assignments=assignments,
        default_assignments=default_assignments,
        keep_clause=keep_clause,
        input_dataset=input_dataset,
        output_dataset=output_dataset,
        study_id=study_id,
    )
    return payload


def write_sas_file(code: str, path: str | Path) -> None:
    file_path = Path(path)
    file_path.parent.mkdir(parents=True, exist_ok=True)
    with file_path.open("w", encoding="utf-8") as handle:
        handle.write(code)


def _default_missing(domain: SDTMDomain, config: MappingConfig) -> list[str]:
    defaults: list[str] = []
    mapped = config.target_variables
    for variable in domain.variables:
        if variable.name in mapped and (variable.core or "").strip().lower() == "req":
            continue
        if (variable.core or "").strip().lower() != "req":
            continue
        defaults.append(_default_line(variable))
    return defaults


def _default_line(variable) -> str:
    if variable.type.lower() == "num":
        return f"{variable.name} = .;"
    return f"{variable.name} = '';"


def _assignment_for_mapping(mapping, domain: SDTMDomain) -> str:
    lookup = {var.name: var for var in domain.variables}
    variable = lookup.get(mapping.target_variable)
    return render_assignment(mapping, variable)
