//! Third-Party Licenses dialog viewport.
//!
//! Displays open source licenses for all third-party dependencies.

use egui::{Context, ScrollArea, Vec2, ViewportBuilder, ViewportId};
use egui_commonmark::{CommonMarkCache, CommonMarkViewer};

use crate::state::ThirdPartyUiState;

/// The viewport ID for the third-party licenses dialog.
const THIRD_PARTY_VIEWPORT_ID: &str = "third_party_dialog";

/// Embedded third-party licenses markdown (generated by cargo-about).
const LICENSES_MD: &str = include_str!("../../../../THIRD_PARTY_LICENSES.md");

/// Show the third-party licenses dialog as a viewport.
pub fn show_third_party_dialog(
    ctx: &Context,
    state: &mut ThirdPartyUiState,
    cache: &mut CommonMarkCache,
) {
    if !state.open {
        return;
    }

    let mut should_close = false;

    ctx.show_viewport_immediate(
        ViewportId::from_hash_of(THIRD_PARTY_VIEWPORT_ID),
        ViewportBuilder::default()
            .with_title("Third-Party Licenses")
            .with_inner_size(Vec2::new(700.0, 600.0))
            .with_min_inner_size(Vec2::new(500.0, 400.0))
            .with_resizable(true)
            .with_close_button(true),
        |ctx, _class| {
            // Handle window close button
            if ctx.input(|i| i.viewport().close_requested()) {
                should_close = true;
            }

            egui::CentralPanel::default().show(ctx, |ui| {
                // Scrollable markdown content
                ScrollArea::vertical()
                    .auto_shrink([false, false])
                    .show(ui, |ui| {
                        CommonMarkViewer::new().show(ui, cache, LICENSES_MD);
                    });

                ui.add_space(8.0);

                // Close button at bottom
                ui.with_layout(egui::Layout::right_to_left(egui::Align::BOTTOM), |ui| {
                    if ui.button("Close").clicked() {
                        should_close = true;
                    }
                });
            });
        },
    );

    if should_close {
        state.close();
    }
}
